name: Spotify → Slack Status

on:
  schedule:
    - cron: "*/5 * * * *" # Executa a cada 5 minutos
  workflow_dispatch:      # Permite rodar manualmente

jobs:
  update-slack-status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Get Spotify access token (refresh)
        id: token
        run: |
          # Solicita novo access_token com refresh_token
          RESPONSE=$(curl -s -u "${{ secrets.SPOTIFY_CLIENT_ID }}:${{ secrets.SPOTIFY_CLIENT_SECRET }}" \
            -d grant_type=refresh_token \
            -d refresh_token="${{ secrets.SPOTIFY_REFRESH_TOKEN }}" \
            https://accounts.spotify.com/api/token)

          ACCESS_TOKEN=$(echo "$RESPONSE" | jq -r '.access_token // empty')

          if [ -z "$ACCESS_TOKEN" ]; then
            echo "Failed to refresh Spotify access token: $RESPONSE"
            exit 1
          fi

          echo "access_token=$ACCESS_TOKEN" >> $GITHUB_OUTPUT

      - name: Get currently playing track from Spotify
        id: spotify
        run: |
          HTTP_STATUS=$(curl -s -o current_track.json -w "%{http_code}" -X GET "https://api.spotify.com/v1/me/player/currently-playing" \
            -H "Authorization: Bearer ${{ steps.token.outputs.access_token }}" \
            -H "Accept: application/json")

          echo "http_status=$HTTP_STATUS" >> $GITHUB_OUTPUT

          # 204 = nothing playing / no content
          if [ "$HTTP_STATUS" = "204" ]; then
            echo "is_playing=false" >> $GITHUB_OUTPUT
            exit 0
          fi

      - name: Extract track and artist
        id: extract
        run: |
          TRACK_NAME=$(jq -r '.item.name // empty' current_track.json)
          ARTIST_NAME=$(jq -r '.item.artists[0].name // empty' current_track.json)
          IS_PLAYING=$(jq -r '.is_playing // false' current_track.json)

          echo "track_name=$TRACK_NAME" >> $GITHUB_OUTPUT
          echo "artist_name=$ARTIST_NAME" >> $GITHUB_OUTPUT
          echo "is_playing=$IS_PLAYING" >> $GITHUB_OUTPUT

      - name: Update Slack status (set)
        if: steps.extract.outputs.is_playing == 'true'
        env:
          TRACK_NAME: ${{ steps.extract.outputs.track_name }}
          ARTIST_NAME: ${{ steps.extract.outputs.artist_name }}
        run: |
          STATUS_TEXT="🎶 Ouvindo: ${TRACK_NAME} — ${ARTIST_NAME}"
          curl -s -X POST "https://slack.com/api/users.profile.set" \
            -H "Authorization: Bearer ${{ secrets.SLACK_ACCESS_TOKEN }}" \
            -H "Content-Type: application/json; charset=utf-8" \
            --data-raw "{
              \"profile\": {
                \"status_text\": \"${STATUS_TEXT}\",
                \"status_emoji\": \":notes:\",
                \"status_expiration\": 0
              }
            }"

      - name: Update Slack status (clear)
        if: steps.extract.outputs.is_playing != 'true'
        run: |
          curl -s -X POST "https://slack.com/api/users.profile.set" \
            -H "Authorization: Bearer ${{ secrets.SLACK_ACCESS_TOKEN }}" \
            -H "Content-Type: application/json; charset=utf-8" \
            --data-raw "{
              \"profile\": {
                \"status_text\": \"\",
                \"status_emoji\": \"\",
                \"status_expiration\": 0
              }
            }"